import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Game from "../Components/Board";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>TIC | TAC | TOE</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Game />
			</main>

			<footer>
				<Link href="/">
					<a>TIC-TIC-TOE © 2022</a>
				</Link>
				<Link href="https://github.com/Super-Nat?tab=repositories">
					<a target="_blank">Github</a>
				</Link>
				<Link href="https://www.linkedin.com/in/natchapon-hemathulin-a5420a230/">
					<a target="_blank">LinkIn</a>
				</Link>
			</footer>
		</>
	);
};

export default Home;
